create table Todo_Todo (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	todoId LONG not null primary key,
	title VARCHAR(80) null,
	todoBooleanStat BOOLEAN,
	todoDateTime DATE null,
	todoDocumentLibrary VARCHAR(512) null,
	todoDouble DOUBLE,
	todoInteger INTEGER,
	todoRichText TEXT null,
	todoText TEXT null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	urlTitle VARCHAR(75) null,
	todoTitleName VARCHAR(255) null,
	todoSummaryName TEXT null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);