/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sb.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Todo service. Represents a row in the &quot;Todo_Todo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sb.test.model.impl.TodoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sb.test.model.impl.TodoImpl</code>.
 * </p>
 *
 * @author "diegofurtado"
 * @see Todo
 * @generated
 */
@ProviderType
public interface TodoModel
	extends BaseModel<Todo>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a todo model instance should use the {@link Todo} interface instead.
	 */

	/**
	 * Returns the primary key of this todo.
	 *
	 * @return the primary key of this todo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this todo.
	 *
	 * @param primaryKey the primary key of this todo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this todo.
	 *
	 * @return the mvcc version of this todo
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this todo.
	 *
	 * @param mvccVersion the mvcc version of this todo
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this todo.
	 *
	 * @return the uuid of this todo
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this todo.
	 *
	 * @param uuid the uuid of this todo
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the todo ID of this todo.
	 *
	 * @return the todo ID of this todo
	 */
	public long getTodoId();

	/**
	 * Sets the todo ID of this todo.
	 *
	 * @param todoId the todo ID of this todo
	 */
	public void setTodoId(long todoId);

	/**
	 * Returns the title of this todo.
	 *
	 * @return the title of this todo
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this todo.
	 *
	 * @param title the title of this todo
	 */
	public void setTitle(String title);

	/**
	 * Returns the todo boolean stat of this todo.
	 *
	 * @return the todo boolean stat of this todo
	 */
	public boolean getTodoBooleanStat();

	/**
	 * Returns <code>true</code> if this todo is todo boolean stat.
	 *
	 * @return <code>true</code> if this todo is todo boolean stat; <code>false</code> otherwise
	 */
	public boolean isTodoBooleanStat();

	/**
	 * Sets whether this todo is todo boolean stat.
	 *
	 * @param todoBooleanStat the todo boolean stat of this todo
	 */
	public void setTodoBooleanStat(boolean todoBooleanStat);

	/**
	 * Returns the todo date time of this todo.
	 *
	 * @return the todo date time of this todo
	 */
	public Date getTodoDateTime();

	/**
	 * Sets the todo date time of this todo.
	 *
	 * @param todoDateTime the todo date time of this todo
	 */
	public void setTodoDateTime(Date todoDateTime);

	/**
	 * Returns the todo document library of this todo.
	 *
	 * @return the todo document library of this todo
	 */
	@AutoEscape
	public String getTodoDocumentLibrary();

	/**
	 * Sets the todo document library of this todo.
	 *
	 * @param todoDocumentLibrary the todo document library of this todo
	 */
	public void setTodoDocumentLibrary(String todoDocumentLibrary);

	/**
	 * Returns the todo double of this todo.
	 *
	 * @return the todo double of this todo
	 */
	public double getTodoDouble();

	/**
	 * Sets the todo double of this todo.
	 *
	 * @param todoDouble the todo double of this todo
	 */
	public void setTodoDouble(double todoDouble);

	/**
	 * Returns the todo integer of this todo.
	 *
	 * @return the todo integer of this todo
	 */
	public int getTodoInteger();

	/**
	 * Sets the todo integer of this todo.
	 *
	 * @param todoInteger the todo integer of this todo
	 */
	public void setTodoInteger(int todoInteger);

	/**
	 * Returns the todo rich text of this todo.
	 *
	 * @return the todo rich text of this todo
	 */
	@AutoEscape
	public String getTodoRichText();

	/**
	 * Sets the todo rich text of this todo.
	 *
	 * @param todoRichText the todo rich text of this todo
	 */
	public void setTodoRichText(String todoRichText);

	/**
	 * Returns the todo text of this todo.
	 *
	 * @return the todo text of this todo
	 */
	@AutoEscape
	public String getTodoText();

	/**
	 * Sets the todo text of this todo.
	 *
	 * @param todoText the todo text of this todo
	 */
	public void setTodoText(String todoText);

	/**
	 * Returns the group ID of this todo.
	 *
	 * @return the group ID of this todo
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this todo.
	 *
	 * @param groupId the group ID of this todo
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this todo.
	 *
	 * @return the company ID of this todo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this todo.
	 *
	 * @param companyId the company ID of this todo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this todo.
	 *
	 * @return the user ID of this todo
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this todo.
	 *
	 * @param userId the user ID of this todo
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this todo.
	 *
	 * @return the user uuid of this todo
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this todo.
	 *
	 * @param userUuid the user uuid of this todo
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this todo.
	 *
	 * @return the user name of this todo
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this todo.
	 *
	 * @param userName the user name of this todo
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this todo.
	 *
	 * @return the create date of this todo
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this todo.
	 *
	 * @param createDate the create date of this todo
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this todo.
	 *
	 * @return the modified date of this todo
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this todo.
	 *
	 * @param modifiedDate the modified date of this todo
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the url title of this todo.
	 *
	 * @return the url title of this todo
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this todo.
	 *
	 * @param urlTitle the url title of this todo
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the todo title name of this todo.
	 *
	 * @return the todo title name of this todo
	 */
	@AutoEscape
	public String getTodoTitleName();

	/**
	 * Sets the todo title name of this todo.
	 *
	 * @param todoTitleName the todo title name of this todo
	 */
	public void setTodoTitleName(String todoTitleName);

	/**
	 * Returns the todo summary name of this todo.
	 *
	 * @return the todo summary name of this todo
	 */
	@AutoEscape
	public String getTodoSummaryName();

	/**
	 * Sets the todo summary name of this todo.
	 *
	 * @param todoSummaryName the todo summary name of this todo
	 */
	public void setTodoSummaryName(String todoSummaryName);

	/**
	 * Returns the status of this todo.
	 *
	 * @return the status of this todo
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this todo.
	 *
	 * @param status the status of this todo
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this todo.
	 *
	 * @return the status by user ID of this todo
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this todo.
	 *
	 * @param statusByUserId the status by user ID of this todo
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this todo.
	 *
	 * @return the status by user uuid of this todo
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this todo.
	 *
	 * @param statusByUserUuid the status by user uuid of this todo
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this todo.
	 *
	 * @return the status by user name of this todo
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this todo.
	 *
	 * @param statusByUserName the status by user name of this todo
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this todo.
	 *
	 * @return the status date of this todo
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this todo.
	 *
	 * @param statusDate the status date of this todo
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the trash entry created when this todo was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this todo.
	 *
	 * @return the trash entry created when this todo was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this todo.
	 *
	 * @return the class primary key of the trash entry for this todo
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this todo.
	 *
	 * @return the trash handler for this todo
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this todo is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this todo is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this todo is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this todo is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this todo is approved.
	 *
	 * @return <code>true</code> if this todo is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this todo is denied.
	 *
	 * @return <code>true</code> if this todo is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this todo is a draft.
	 *
	 * @return <code>true</code> if this todo is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this todo is expired.
	 *
	 * @return <code>true</code> if this todo is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this todo is inactive.
	 *
	 * @return <code>true</code> if this todo is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this todo is incomplete.
	 *
	 * @return <code>true</code> if this todo is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this todo is pending.
	 *
	 * @return <code>true</code> if this todo is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this todo is scheduled.
	 *
	 * @return <code>true</code> if this todo is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}